# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ADMIN/Vivado_project/r_type_datapath/r_type_datapath.cache/wt [current_project]
set_property parent.project_path C:/Users/ADMIN/Vivado_project/r_type_datapath/r_type_datapath.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ADMIN/Vivado_project/r_type_datapath/r_type_datapath.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ADMIN/Vivado_project/alu_unit/alu_unit.srcs/sources_1/new/alu_unit.v
  C:/Users/ADMIN/Vivado_project/instruction_fetch/instruction_fetch.srcs/sources_1/new/instruction_fetch.v
  C:/Users/ADMIN/Vivado_project/instruction_memory/instruction_memory.srcs/sources_1/new/instruction_memory.v
  C:/Users/ADMIN/Vivado_project/pc_counter/pc_counter.srcs/sources_1/new/pc_counter.v
  C:/Users/ADMIN/Vivado_project/program_counter/program_counter.srcs/sources_1/new/program_counter.v
  C:/Users/ADMIN/Vivado_project/Register_file/Register_file.srcs/sources_1/new/register_file.v
  C:/Users/ADMIN/Vivado_project/r_type_datapath/r_type_datapath.srcs/sources_1/new/r_type_datapath.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top r_type_datapath -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef r_type_datapath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file r_type_datapath_utilization_synth.rpt -pb r_type_datapath_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
